/**
 * Mechanical per-install capability discovery.
 *
 * n2 of docs/plans/gateway-passthrough-policy.dag.toml. The gateway learns what
 * a provider CLI accepts by ASKING THE INSTALLED BINARY, not by consulting a
 * list a human typed on a different machine. A hand-authored flag list is wrong
 * on every customer machine that differs from the author's, which is the defect
 * that removed capability from customers three times.
 *
 * SOURCE 1 of 3: shell completions.
 *
 * Measured on the installed binaries, 2026-08-18:
 *
 *                  --help flags   completion flags
 *     grok               48             116
 *     codex              23              97
 *
 * Completions are generated by the CLI itself, cover the whole command tree in
 * one call, and INCLUDE FLAGS HIDDEN FROM HELP. Every grok flag invisible to
 * `--help` appears here, including `--compaction-mode`, `--compaction-detail`,
 * `--effort` and `--reasoning-effort`. That last pair is exactly where a
 * hand-maintained contract had invented an enum the binary does not have.
 *
 * Subcommand spelling differs (`grok completions`, `codex completion`), so both
 * are attempted. claude, vibe, devin, cursor-agent and agy ship none at their
 * current versions; those fall through to the later sources.
 *
 * PROBE SAFETY, which is a structural property here and not a convention:
 * generating a completion script is a pure emit. It reaches no model, starts no
 * session and consumes no quota. Sources 2 and 3 (help traversal, invalid-value
 * probe) carry the stronger requirement that the invocation must fail at
 * ARGUMENT PARSING before dispatch, because a probe that becomes a valid
 * invocation is billed: `claude completion` reached the model during this
 * investigation because `completion` is not a claude subcommand and parsed as a
 * prompt.
 */

/** One command node in a provider's discovered command tree. */
export interface DiscoveredCommand {
  /** Command path from the root, e.g. [] for root, ["agent"] for `grok agent`. */
  readonly path: readonly string[];
  /**
   * Whether `path` is trustworthy.
   *
   * clap encodes the command path in a shell variable, and the encoding differs
   * by version. grok 1.0.4 uses an unambiguous `root__subcmd__child`. codex-cli
   * 0.147.0 uses a bare `root__child`, where `__` ALSO replaces a dash inside a
   * command name: `codex__app__server__daemon__disable__remote__control` is
   * `codex app-server daemon disable-remote-control`, and nothing in the string
   * says which `__` is a separator and which is a dash.
   *
   * So the path is reported as "ambiguous" rather than guessed. The flag SET is
   * unaffected and is what the builder needs; inventing a wrong command path
   * would be the gateway making up an answer, which is the habit this whole
   * subsystem exists to remove.
   */
  readonly pathConfidence: "exact" | "ambiguous";
  /** Long flags this command accepts, e.g. "--output-format". Sorted, unique. */
  readonly flags: readonly string[];
  /** Short flags, e.g. "-p". Sorted, unique. */
  readonly shortFlags: readonly string[];
  /** Subcommand names reachable from this command. Sorted, unique. */
  readonly subcommands: readonly string[];
}

/** What one discovery source could determine about a provider. */
export interface DiscoveryResult {
  readonly source: "completions";
  /** Every command node found, root first. */
  readonly commands: readonly DiscoveredCommand[];
  /**
   * Why a source produced nothing, when it produced nothing. Load-bearing under
   * the fail-open policy: "could not parse" and "parsed, and the flag is absent"
   * are DIFFERENT facts, and only the second is evidence about the binary.
   */
  readonly unparsed: string | null;
}

/**
 * clap encodes the command path in the `cmd` variable, with two spellings in
 * the wild. The explicit one is unambiguous; the bare one is not, because it
 * also stands in for a dash inside a command name.
 */
const CMD_PATH_SEPARATOR_EXPLICIT = "__subcmd__";
const CMD_PATH_SEPARATOR_BARE = "__";

/**
 * Parse a clap-generated bash completion script into a command tree.
 *
 * Shape being parsed, verified against grok 1.0.4 and codex-cli 0.147.0:
 *
 *     case "${cmd}" in
 *         grok)
 *             opts="-p -h --output-format --effort ... [PROMPT] agent inspect ..."
 *         grok__subcmd__agent)
 *             opts="-m -h --model --effort ... stdio headless serve"
 *
 * `opts` mixes long flags, short flags, positional placeholders (`[PROMPT]`,
 * `<PATH>`) and subcommand names. They are separated here rather than returned
 * as one bag, because a subcommand name and a positional placeholder are not
 * flags and would otherwise be offered to a caller as if they were.
 *
 * Returns `null` when the text is not a clap bash completion, so the caller can
 * record "unparsed" distinctly from "parsed, nothing found".
 */
export function parseClapBashCompletion(
  script: string,
  rootName: string
): DiscoveredCommand[] | null {
  if (!script.includes('case "${cmd}" in') && !script.includes('case "${cmd}" in')) return null;

  const commands: DiscoveredCommand[] = [];
  // Each arm is `<cmdName>)` on its own line, followed within a few lines by an
  // `opts="..."` assignment. Anchoring on the arm rather than scanning for all
  // `opts=` keeps a flag attributed to the command that actually accepts it.
  const armPattern = /^\s{0,16}([A-Za-z0-9_.:-]+)\)\s*$/gm;
  let arm: RegExpExecArray | null;
  while ((arm = armPattern.exec(script)) !== null) {
    const cmdName = arm[1];
    if (cmdName !== rootName && !cmdName.startsWith(`${rootName}${CMD_PATH_SEPARATOR_BARE}`))
      continue;

    const rest = script.slice(arm.index);
    const opts = /opts="([^"]*)"/.exec(rest);
    if (!opts) continue;

    let path: string[] = [];
    let pathConfidence: "exact" | "ambiguous" = "exact";
    if (cmdName !== rootName) {
      const explicitPrefix = `${rootName}${CMD_PATH_SEPARATOR_EXPLICIT}`;
      if (cmdName.startsWith(explicitPrefix)) {
        path = cmdName.slice(explicitPrefix.length).split(CMD_PATH_SEPARATOR_EXPLICIT);
      } else {
        path = cmdName
          .slice(rootName.length + CMD_PATH_SEPARATOR_BARE.length)
          .split(CMD_PATH_SEPARATOR_BARE);
        pathConfidence = "ambiguous";
      }
    }

    const flags = new Set<string>();
    const shortFlags = new Set<string>();
    const subcommands = new Set<string>();
    for (const token of opts[1].split(/\s+/)) {
      if (!token) continue;
      // A positional placeholder, not a capability the caller can pass.
      if (token.startsWith("[") || token.startsWith("<")) continue;
      if (token.startsWith("--")) {
        // Guard against a malformed `----reauthenticate` seen in grok's own
        // output: keep it verbatim rather than silently normalising, because a
        // normalisation here would be the gateway editing upstream's answer.
        flags.add(token);
      } else if (token.startsWith("-")) {
        shortFlags.add(token);
      } else {
        subcommands.add(token);
      }
    }
    commands.push({
      path,
      pathConfidence,
      flags: [...flags].sort(),
      shortFlags: [...shortFlags].sort(),
      subcommands: [...subcommands].sort(),
    });
  }
  return commands.length > 0 ? commands : null;
}

/** Every long flag in the tree, deduplicated. Convenience for coverage checks. */
export function allFlags(commands: readonly DiscoveredCommand[]): string[] {
  const out = new Set<string>();
  for (const c of commands) for (const f of c.flags) out.add(f);
  return [...out].sort();
}

// ---------------------------------------------------------------------------
// SOURCE 2: the help-text scrape.
//
// Deliberately the dumbest step in the pipeline. It does not parse help, does
// not detect a dialect, and is not trying to be right. It collects every
// `--token` in the text and hands the lot to the probe, which asks the binary
// itself which of them are real. One regex, no per-provider branch, no format
// understanding, because the intelligence belongs in the binary and the data
// belongs in a table; anything in between is plumbing that would otherwise need
// maintaining per provider per version, which is the hand-authored provider
// data the policy forbids.
//
// OVER-COLLECTION IS THE DESIGN, NOT A TOLERATED FLAW. A candidate scraped out
// of prose costs exactly one probe, and the probe answers `absent`, and
// `absence-is-never-subtractive` means an absent verdict removes nothing. The
// error that would matter is the other direction, missing a real flag, and a
// regex that reads every token cannot miss one that is written down. Real
// example, vibe's help wraps mid-flag: "pass --auto-\napprove or --yolo",
// yielding the non-flag `--auto`. It probes absent and nothing happens.
//
// READ BOTH STREAMS. Candidates from `--help`, measured 2026-08-18:
//
//                    stdout only   stdout+stderr
//       grok               48            48
//       codex              23            23
//       claude             65            65
//       vibe               21            21
//       devin              12            12
//       cursor-agent       26            26
//       gemini             29            29
//       agy                 0            20
//
// agy is a Go `flag` binary and Go writes usage to STDERR, so a stdout-only
// read reports a provider with no flags at all rather than a read that failed.
// That is the fail-open distinction at its most concrete: zero candidates from
// an empty read is evidence about our plumbing, never about the binary, and a
// caller that conflates the two removes every agy flag on the strength of
// having looked at the wrong file descriptor.
// ---------------------------------------------------------------------------

/**
 * Every `--token`, in one regex.
 *
 * Requires a leading alphanumeric, so a bare `--` end-of-options marker is not
 * a candidate. Requires a trailing alphanumeric, so a token broken by a line
 * wrap (`--auto-`) yields `--auto` rather than a name no parser would accept; a
 * trailing hyphen is a token boundary, not a fact about the dialect.
 *
 * Consequence worth stating: grok emits a malformed `----reauthenticate` in its
 * own completion output, and this yields `--reauthenticate` from it. Source 1
 * keeps that token verbatim on purpose. Here the scrape is only nominating
 * candidates, both spellings are cheap to probe, and the binary settles it.
 */
const CANDIDATE_FLAG = /--[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?/g;

/**
 * Nominate candidate flags from a binary's help output.
 *
 * Pass BOTH stdout and stderr concatenated; see the stream note above.
 *
 * Returns candidates, not capability. An empty result means this text named no
 * flags, which is NOT the same fact as "the binary has no flags" and must never
 * be recorded as one. The caller owns that distinction because only the caller
 * knows whether the read succeeded.
 */
export function scrapeCandidateFlags(helpText: string): string[] {
  return [...new Set(helpText.match(CANDIDATE_FLAG) ?? [])].sort();
}

// ---------------------------------------------------------------------------
// SOURCE 3: the invalid-value probe.
//
// Answers two questions completions cannot: does this flag EXIST on the
// installed binary, and does it carry a REAL value set? That second question is
// the one that matters most, because a contract `values` list is enforced as a
// REJECTION list, so an invented one refuses input the binary accepts. grok
// `--effort` carried a five-level enum the binary has never had.
//
// The discriminator, verified against grok 1.0.4:
//
//   grok --not-a-real-flag ZZZ  -> "unexpected argument"           ABSENT
//   grok --permission-mode ZZZ  -> "invalid value ... [possible values: ...]"
//                                                                  PRESENT + enum
//   grok --compaction-mode ZZZ  -> falls through to another error   PRESENT, no enum
//
// The control is load bearing and easy to omit. clap reports an enum violation
// IN PREFERENCE TO the missing-value error, so for a flag that has a value set
// the enum message wins. The ABSENCE of that message is the signal, which means
// a probe run without a known-enum control cannot distinguish "no constraint"
// from "the constraint fired but a different error printed first".
// ---------------------------------------------------------------------------

/** Whether the flag takes a value, as reported by the binary's own parser. */
export type ProbedArity = "none" | "one" | "unknown";

/** What a probe concluded about one flag on the installed binary. */
export type FlagProbeVerdict =
  /** The binary rejected the flag itself. */
  | { kind: "absent" }
  /** The flag exists and constrains its value; these are the accepted values. */
  | { kind: "present"; arity: ProbedArity; values: readonly string[] }
  /** The flag exists; no enum to enforce (or none the parser disclosed). */
  | { kind: "present"; arity: ProbedArity; values: null }
  /**
   * The probe could not tell. Under the fail-open policy this must stay
   * DISTINCT from `absent`: absent is evidence about the binary, unparsed is
   * evidence about our parser, and treating the second as the first is how a
   * discovery system starts silently removing capability.
   */
  | { kind: "unparsed"; reason: string };

/**
 * Interpret a CLI's stderr from a deliberately-invalid probe invocation.
 *
 * FOUR DIALECTS, ONE FUNCTION, NO PER-PROVIDER BRANCH. Every pattern below is
 * matched on the MESSAGE, not on who emitted it, so a provider that switches
 * argument parser between versions is handled without a code change. Measured
 * verbatim on the installed binaries 2026-08-18:
 *
 *   clap       grok 1.0.4, devin 3000.4.25
 *   argparse   vibe 2.14.1
 *   Go flag    agy
 *   commander  cursor-agent
 *
 * THE ANCHOR CUTS BOTH WAYS, which is the finding that shaped this function.
 * The probe argv is `[--flag=ZZZ, --anchor]` and the anchor is missing its
 * value, so every probe produces an error from SOMEWHERE. Which error surfaces
 * depends on the dialect's reporting order, and the two orders mean opposite
 * things:
 *
 *   clap validates left to right and reports the first failure. Reaching the
 *   anchor's "a value is required" therefore PROVES the flag under test parsed
 *   clean. Measured: `--permission-mode=ZZZ --model` returns the enum error,
 *   `--not-real-xyz=ZZZ --model` returns "unexpected argument", and only
 *   `--effort=ZZZ --model` reaches the anchor.
 *
 *   argparse, Go flag and commander report an UNKNOWN FLAG last, after the
 *   missing-argument check. Reaching the anchor there proves nothing: the flag
 *   may have parsed clean, or may not exist at all. Measured on agy, where
 *   `--effort=ZZZ --model`, `--mode=ZZZ --model` and `--not-real-xyz=ZZZ
 *   --model` return BYTE-IDENTICAL stderr.
 *
 * So those three anchor messages return `unparsed`, not `present`. Reading them
 * as `present` is not a harmless over-report: it fabricates arity for a flag
 * that does not exist, and it did exactly that for every agy candidate before
 * this was measured.
 *
 * The fall-through is `unparsed` for the same reason. Under fail-open an
 * unparsed flag is still offered to the caller and still adjudicated by the
 * binary, so nothing is lost by declining to guess; inventing `arity: "one"`
 * for an unrecognised message loses the distinction the whole policy rests on.
 */
/**
 * The one line that names a rejected flag.
 *
 * Read the LINE, never the whole output. Several binaries print their full help
 * to stdout alongside the error, and that help lists every flag they have, so a
 * naming test over the combined streams says "this message names the flag under
 * test" for a flag that parsed perfectly. Measured: it turned 22 real grok flags
 * into absent verdicts, which is a fabricated removal 22 times over.
 */
const REJECTION_LINE =
  /^.*(?:unexpected argument|unrecognized arguments?:|flags? provided but not defined|unknown option).*$/im;

/**
 * Whether a line names this flag as a token.
 *
 * Both spellings, because Go's flag package prints `-add-dir` for what its own
 * help calls `--add-dir`. Token-bounded, because a substring test lets `--all`
 * match inside `--allowed-tools`.
 */
function namesToken(line: string, flag: string): boolean {
  const bare = flag.replace(/^-+/u, "").replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
  return new RegExp(`(^|[^\\w-])--?${bare}(?![\\w-])`, "u").test(line);
}

/**
 * The diagnostic ABOUT THIS FLAG: the first marker line that names it, plus the
 * line after, which is where clap wraps a value set.
 *
 * Three attempts got here. Reading the whole output let help text donate another
 * flag's enum. Anchoring on any line containing "error" caught a
 * "(os error 30)" warning. Anchoring on a marker at line start still caught
 * Node's `Error: EROFS: ...` and `WARNING: invalid value for config key ...`,
 * because a warning is allowed to look exactly like a diagnostic.
 *
 * So stop trying to recognise a diagnostic by its shape. The one we want is the
 * one that MENTIONS THE FLAG WE ASKED ABOUT, and every rule below already
 * requires that. If no marker line names it, there is no diagnostic about it and
 * the naming rules downstream decide on the rejection line alone.
 */
const DIAGNOSTIC_MARKER =
  /error:|invalid (?:value|choice|boolean value)|unexpected (?:argument|value)|unrecognized arguments?:|flags? provided but not defined|unknown option|ignored explicit argument/i;

function diagnosticBlock(text: string, flag: string): string {
  const lines = text.split("\n");
  const index = lines.findIndex(line => DIAGNOSTIC_MARKER.test(line) && namesToken(line, flag));
  return index === -1 ? "" : lines.slice(index, index + 2).join("\n");
}

export interface ProbeContext {
  /** The flag being asked about. */
  readonly flag: string;
  /** The sentinel flag, which is guaranteed not to exist on any binary. */
  readonly sentinel: string;
}

/**
 * `context` is REQUIRED. Every dialect's rejection message names a flag, and
 * with a sentinel in the argv there is always one to name, so a reading that
 * ignores WHICH flag was named calls every real flag absent. That mistake
 * fabricates a removal, which is the one outcome this subsystem exists to
 * prevent.
 */
export function interpretProbeOutput(stderr: string, context: ProbeContext): FlagProbeVerdict {
  const text = stderr.trim();
  if (!text) return { kind: "unparsed", reason: "probe produced no diagnostic output" };
  const rejectionLine = REJECTION_LINE.exec(text)?.[0] ?? "";
  const namesFlag = namesToken(rejectionLine, context.flag);
  const namesSentinel = namesToken(rejectionLine, context.sentinel);
  // Every PRESENT verdict below reads this and requires the diagnostic to name
  // the flag under test. A message about some other flag is evidence about that
  // flag, and reading it as evidence about this one invents a capability.
  const diagnostic = diagnosticBlock(text, context.flag);
  const diagnosticNamesFlag = diagnostic !== "";

  // PRESENT, ARITY NONE: the flag exists and takes no value, so supplying one
  // is itself the error. Only the inline `=` form surfaces this; see
  // buildProbeArgv.
  //   clap       unexpected value 'ZZZ' for '--always-approve' found; no more were expected
  //   argparse   argument --auto-approve/--yolo: ignored explicit argument 'ZZZ'
  if (
    diagnosticNamesFlag &&
    (/unexpected value/i.test(diagnostic) || /ignored explicit argument/i.test(diagnostic))
  )
    return { kind: "present", arity: "none", values: null };

  // PRESENT, ARITY ONE, WITH A REAL VALUE SET. This is the verdict that matters
  // most: `values` is enforced as a rejection list, so an invented set refuses
  // input the binary accepts, which is the grok `--effort` defect exactly.
  //   clap       invalid value 'ZZZ' for '--mode <MODE>'
  //                [possible values: a, b]
  //   argparse   argument --output: invalid choice: 'ZZZ' (choose from 'text', 'json')
  const clapValues = diagnosticNamesFlag
    ? /\[possible values:\s*([^\]]+)\]/i.exec(diagnostic)
    : null;
  if (clapValues) return { kind: "present", arity: "one", values: splitValues(clapValues[1]) };
  const argparseValues = diagnosticNamesFlag
    ? /choose from\s*\(?([^)]+)\)/i.exec(diagnostic)
    : null;
  if (argparseValues)
    return { kind: "present", arity: "one", values: splitValues(argparseValues[1]) };

  // PRESENT, ARITY ONE, SET UNDISCLOSED. An invalid-value complaint with no
  // enumeration still proves the flag exists and constrains its value.
  if (
    diagnosticNamesFlag &&
    (/invalid value/i.test(diagnostic) || /invalid choice/i.test(diagnostic))
  )
    return { kind: "present", arity: "one", values: null };

  // PRESENT, ARITY NONE, Go flag. A bool given a value complains about the
  // value, which proves the flag exists.
  //   Go flag    invalid boolean value "ZZZ" for -sandbox
  if (diagnosticNamesFlag && /invalid boolean value/i.test(diagnostic))
    return { kind: "present", arity: "none", values: null };

  // THE REJECTION MESSAGE, READ BY WHICH FLAG IT NAMES.
  //   clap       error: unexpected argument '--nope' found
  //   argparse   vibe: error: unrecognized arguments: --nope=ZZZ --sentinel
  //   Go flag    flags provided but not defined: -nope -sentinel
  //   commander  error: unknown option '--nope'
  //
  // Naming ONLY the sentinel means the parser accepted the flag under test and
  // went on to reject the one we know does not exist.
  const rejected = rejectionLine !== "";
  // ARITY ONE, and this is an inference rather than a message. The flag under
  // test was given `=VALUE` and the parser did not complain about it, so it
  // takes a value: every dialect here rejects a value on a no-value flag, with
  // "unexpected value" (clap), "ignored explicit argument" (argparse),
  // "invalid boolean value" (Go) or "unknown option" (commander), all of which
  // are handled above.
  if (rejected && namesSentinel && !namesFlag)
    return { kind: "present", arity: "one", values: null };
  if (rejected && namesFlag) {
    // COMMANDER IS AMBIGUOUS AND MUST NOT BE FORCED. claude and cursor-agent
    // report a real BOOLEAN given `=value` as `unknown option '--continue=ZZZ'`,
    // byte-identical to a flag that does not exist. Reading that as absent
    // would fabricate a removal for every boolean flag claude has.
    if (/unknown option/i.test(text))
      return {
        kind: "unparsed",
        reason: "commander reports a real boolean given a value exactly like an absent flag",
      };
    return { kind: "absent" };
  }

  return { kind: "unparsed", reason: "unrecognised diagnostic; declining to guess arity" };
}

/** Split an enumerated value list, tolerating the quoting argparse adds. */
function splitValues(raw: string): string[] {
  return raw
    .split(",")
    .map(v => v.trim().replace(/^['"]|['"]$/g, ""))
    .filter(Boolean);
}

/**
 * Build the argv for a safe probe of one flag.
 *
 * INLINE `=` FORM, DELIBERATELY. The space form (`--flag ZZZ --anchor`) cannot
 * distinguish a boolean flag from a value-taking one: the sentinel is consumed
 * as a positional and both produce identical stderr. The inline form makes the
 * probe a FOUR-way discriminator that also yields arity. Measured on grok 1.0.4:
 *
 *   --not-a-real-flag=ZZZ  -> "unexpected argument"                  ABSENT
 *   --always-approve=ZZZ   -> "unexpected value ... no more were
 *                             expected"                              present, arity none
 *   --permission-mode=ZZZ  -> "invalid value ... [possible values:]" present, arity one, enum
 *   --effort=ZZZ           -> falls through to the anchor error       present, arity one, no enum
 *
 * All four dialects in play accept `--flag=value` (clap, commander, argparse and
 * Go's flag), so one form covers all seven providers without a per-provider
 * branch, which the policy forbids.
 *
 * SAFETY IS STRUCTURAL. The real invariant is NOT "the anchor must take a
 * value", it is:
 *
 *     NO PROBE ARGV MAY CONTAIN A TOKEN THAT DOES NOT BEGIN WITH `-`.
 *
 * That is what the `claude completion` billing incident actually violated:
 * `completion` was a bare token, so it became a PROMPT and reached the model.
 * A bare token is the only thing that can be consumed as a positional and turn
 * a probe into a real request. The inline form has no bare token by
 * construction, and `assertProbeArgvCannotRun` enforces it.
 *
 * `anchorFlag` should require a value, so the invocation additionally fails on
 * the missing anchor value. That is defence in depth, not the primary guard.
 */
/**
 * A flag guaranteed not to exist on any binary, appended to every probe.
 *
 * d1c. It replaced a value-requiring ANCHOR read from help text, for two
 * reasons. agy prints no value placeholder, so it yielded no anchor and its
 * flags went unasked. And the anchor rests on a flag EXISTING and requiring a
 * value, which is read off the binary and can be wrong; the sentinel rests on a
 * flag NOT existing, which is a property we control.
 *
 * It is also what makes the probe unable to run: an argv containing a flag no
 * parser knows cannot reach dispatch, whatever the flag under test turns out to
 * be.
 */
export const PROBE_SENTINEL = "--zzz-gateway-probe-not-a-flag";

/** Value handed to the flag under test. Never a real value for anything. */
export const PROBE_SENTINEL_VALUE = "ZZZ_GATEWAY_PROBE";

export function buildProbeArgv(
  flag: string,
  commandPath: readonly string[] = [],
  sentinel: string = PROBE_SENTINEL,
  sentinelValue: string = PROBE_SENTINEL_VALUE
): string[] {
  const argv = [...commandPath, `${flag}=${sentinelValue}`, sentinel];
  assertProbeArgvCannotRun(argv, commandPath);
  return argv;
}

/**
 * Throw unless every token is option-shaped.
 *
 * A probe is only safe if the CLI cannot reach dispatch, and the one thing that
 * lets it reach dispatch is a bare token being taken as a positional argument.
 * Enforced here rather than trusted to the caller, because the failure mode is
 * a billed model call and a possible side effect, not a wrong answer.
 */
export function assertProbeArgvCannotRun(
  argv: readonly string[],
  commandPath: readonly string[] = []
): void {
  // The declared subcommand path is the ONLY bare token allowed, and it must
  // match position for position. `codex exec` has to be reachable or the probe
  // reads the root command, where codex accepts flags `exec` does not. Allowing
  // an arbitrary bare token instead would restore exactly the hazard this guard
  // exists for: one consumed as a prompt.
  for (const [index, expected] of commandPath.entries()) {
    if (argv[index] !== expected) {
      throw new Error(
        `unsafe probe argv: expected declared command token ${JSON.stringify(expected)} at ` +
          `position ${index}, found ${JSON.stringify(argv[index])}`
      );
    }
  }
  for (const token of argv.slice(commandPath.length)) {
    if (!token.startsWith("-")) {
      throw new Error(
        `unsafe probe argv: token ${JSON.stringify(token)} is not option-shaped and could be ` +
          `consumed as a positional, turning the probe into a real invocation`
      );
    }
  }
}

// ---------------------------------------------------------------------------
// SOURCE 3, part 2: which flags may be asked at all.
//
// The probe argv is `[--flag=ZZZ, --sentinel]`, and the sentinel is a flag no
// parser knows. Every dialect therefore produces a rejection, and the rejection
// NAMES a flag: only the sentinel when the flag under test parsed clean, both
// when it did not. See interpretProbeOutput.
//
// An earlier version anchored on a value-requiring flag scraped from help. It
// was retired in d1c: agy prints no value placeholder, so it produced no anchor
// and its flags went unasked, and an anchor rests on a flag EXISTING, which is
// read off the binary and can be wrong.
// ---------------------------------------------------------------------------

/**
 * Flags never probed, because probing one could DO something.
 *
 * A boolean flag given `=ZZZ` errors in clap, argparse and Go, but commander
 * accepts and ignores a value, so `--update=ZZZ` can execute. This is a
 * host-safety rule of the same kind as retained_enforcement, not a judgement
 * about capability: these flags stay in the seed, they are simply not asked.
 */
const UNSAFE_TO_PROBE =
  /update|upgrade|install|login|logout|auth|reauth|uninstall|delete|remove|reset|publish|purge/iu;

/** Whether this flag may be probed at all. See UNSAFE_TO_PROBE. */
export function isProbeSafeFlag(flag: string): boolean {
  return !UNSAFE_TO_PROBE.test(flag);
}
