/**
 * Mechanical per-install capability discovery.
 *
 * n2 of docs/plans/gateway-passthrough-policy.dag.toml. The gateway learns what
 * a provider CLI accepts by ASKING THE INSTALLED BINARY, not by consulting a
 * list a human typed on a different machine. A hand-authored flag list is wrong
 * on every customer machine that differs from the author's, which is the defect
 * that removed capability from customers three times.
 *
 * SOURCE 1 of 3: shell completions.
 *
 * Measured on the installed binaries, 2026-08-18:
 *
 *                  --help flags   completion flags
 *     grok               48             116
 *     codex              23              97
 *
 * Completions are generated by the CLI itself, cover the whole command tree in
 * one call, and INCLUDE FLAGS HIDDEN FROM HELP. Every grok flag invisible to
 * `--help` appears here, including `--compaction-mode`, `--compaction-detail`,
 * `--effort` and `--reasoning-effort`. That last pair is exactly where a
 * hand-maintained contract had invented an enum the binary does not have.
 *
 * Subcommand spelling differs (`grok completions`, `codex completion`), so both
 * are attempted. claude, vibe, devin, cursor-agent and agy ship none at their
 * current versions; those fall through to the later sources.
 *
 * PROBE SAFETY, which is a structural property here and not a convention:
 * generating a completion script is a pure emit. It reaches no model, starts no
 * session and consumes no quota. Sources 2 and 3 (help traversal, invalid-value
 * probe) carry the stronger requirement that the invocation must fail at
 * ARGUMENT PARSING before dispatch, because a probe that becomes a valid
 * invocation is billed: `claude completion` reached the model during this
 * investigation because `completion` is not a claude subcommand and parsed as a
 * prompt.
 */

/** One command node in a provider's discovered command tree. */
export interface DiscoveredCommand {
  /** Command path from the root, e.g. [] for root, ["agent"] for `grok agent`. */
  readonly path: readonly string[];
  /**
   * Whether `path` is trustworthy.
   *
   * clap encodes the command path in a shell variable, and the encoding differs
   * by version. grok 1.0.4 uses an unambiguous `root__subcmd__child`. codex-cli
   * 0.147.0 uses a bare `root__child`, where `__` ALSO replaces a dash inside a
   * command name: `codex__app__server__daemon__disable__remote__control` is
   * `codex app-server daemon disable-remote-control`, and nothing in the string
   * says which `__` is a separator and which is a dash.
   *
   * So the path is reported as "ambiguous" rather than guessed. The flag SET is
   * unaffected and is what the builder needs; inventing a wrong command path
   * would be the gateway making up an answer, which is the habit this whole
   * subsystem exists to remove.
   */
  readonly pathConfidence: "exact" | "ambiguous";
  /** Long flags this command accepts, e.g. "--output-format". Sorted, unique. */
  readonly flags: readonly string[];
  /** Short flags, e.g. "-p". Sorted, unique. */
  readonly shortFlags: readonly string[];
  /** Subcommand names reachable from this command. Sorted, unique. */
  readonly subcommands: readonly string[];
}

/** What one discovery source could determine about a provider. */
export interface DiscoveryResult {
  readonly source: "completions";
  /** Every command node found, root first. */
  readonly commands: readonly DiscoveredCommand[];
  /**
   * Why a source produced nothing, when it produced nothing. Load-bearing under
   * the fail-open policy: "could not parse" and "parsed, and the flag is absent"
   * are DIFFERENT facts, and only the second is evidence about the binary.
   */
  readonly unparsed: string | null;
}

/**
 * clap encodes the command path in the `cmd` variable, with two spellings in
 * the wild. The explicit one is unambiguous; the bare one is not, because it
 * also stands in for a dash inside a command name.
 */
const CMD_PATH_SEPARATOR_EXPLICIT = "__subcmd__";
const CMD_PATH_SEPARATOR_BARE = "__";

/**
 * Parse a clap-generated bash completion script into a command tree.
 *
 * Shape being parsed, verified against grok 1.0.4 and codex-cli 0.147.0:
 *
 *     case "${cmd}" in
 *         grok)
 *             opts="-p -h --output-format --effort ... [PROMPT] agent inspect ..."
 *         grok__subcmd__agent)
 *             opts="-m -h --model --effort ... stdio headless serve"
 *
 * `opts` mixes long flags, short flags, positional placeholders (`[PROMPT]`,
 * `<PATH>`) and subcommand names. They are separated here rather than returned
 * as one bag, because a subcommand name and a positional placeholder are not
 * flags and would otherwise be offered to a caller as if they were.
 *
 * Returns `null` when the text is not a clap bash completion, so the caller can
 * record "unparsed" distinctly from "parsed, nothing found".
 */
export function parseClapBashCompletion(
  script: string,
  rootName: string
): DiscoveredCommand[] | null {
  if (!script.includes('case "${cmd}" in') && !script.includes('case "${cmd}" in')) return null;

  const commands: DiscoveredCommand[] = [];
  // Each arm is `<cmdName>)` on its own line, followed within a few lines by an
  // `opts="..."` assignment. Anchoring on the arm rather than scanning for all
  // `opts=` keeps a flag attributed to the command that actually accepts it.
  const armPattern = /^\s{0,16}([A-Za-z0-9_.:-]+)\)\s*$/gm;
  let arm: RegExpExecArray | null;
  while ((arm = armPattern.exec(script)) !== null) {
    const cmdName = arm[1];
    if (cmdName !== rootName && !cmdName.startsWith(`${rootName}${CMD_PATH_SEPARATOR_BARE}`))
      continue;

    const rest = script.slice(arm.index);
    const opts = /opts="([^"]*)"/.exec(rest);
    if (!opts) continue;

    let path: string[] = [];
    let pathConfidence: "exact" | "ambiguous" = "exact";
    if (cmdName !== rootName) {
      const explicitPrefix = `${rootName}${CMD_PATH_SEPARATOR_EXPLICIT}`;
      if (cmdName.startsWith(explicitPrefix)) {
        path = cmdName.slice(explicitPrefix.length).split(CMD_PATH_SEPARATOR_EXPLICIT);
      } else {
        path = cmdName
          .slice(rootName.length + CMD_PATH_SEPARATOR_BARE.length)
          .split(CMD_PATH_SEPARATOR_BARE);
        pathConfidence = "ambiguous";
      }
    }

    const flags = new Set<string>();
    const shortFlags = new Set<string>();
    const subcommands = new Set<string>();
    for (const token of opts[1].split(/\s+/)) {
      if (!token) continue;
      // A positional placeholder, not a capability the caller can pass.
      if (token.startsWith("[") || token.startsWith("<")) continue;
      if (token.startsWith("--")) {
        // Guard against a malformed `----reauthenticate` seen in grok's own
        // output: keep it verbatim rather than silently normalising, because a
        // normalisation here would be the gateway editing upstream's answer.
        flags.add(token);
      } else if (token.startsWith("-")) {
        shortFlags.add(token);
      } else {
        subcommands.add(token);
      }
    }
    commands.push({
      path,
      pathConfidence,
      flags: [...flags].sort(),
      shortFlags: [...shortFlags].sort(),
      subcommands: [...subcommands].sort(),
    });
  }
  return commands.length > 0 ? commands : null;
}

/** Every long flag in the tree, deduplicated. Convenience for coverage checks. */
export function allFlags(commands: readonly DiscoveredCommand[]): string[] {
  const out = new Set<string>();
  for (const c of commands) for (const f of c.flags) out.add(f);
  return [...out].sort();
}

// ---------------------------------------------------------------------------
// SOURCE 3: the invalid-value probe.
//
// Answers two questions completions cannot: does this flag EXIST on the
// installed binary, and does it carry a REAL value set? That second question is
// the one that matters most, because a contract `values` list is enforced as a
// REJECTION list, so an invented one refuses input the binary accepts. grok
// `--effort` carried a five-level enum the binary has never had.
//
// The discriminator, verified against grok 1.0.4:
//
//   grok --not-a-real-flag ZZZ  -> "unexpected argument"           ABSENT
//   grok --permission-mode ZZZ  -> "invalid value ... [possible values: ...]"
//                                                                  PRESENT + enum
//   grok --compaction-mode ZZZ  -> falls through to another error   PRESENT, no enum
//
// The control is load bearing and easy to omit. clap reports an enum violation
// IN PREFERENCE TO the missing-value error, so for a flag that has a value set
// the enum message wins. The ABSENCE of that message is the signal, which means
// a probe run without a known-enum control cannot distinguish "no constraint"
// from "the constraint fired but a different error printed first".
// ---------------------------------------------------------------------------

/** Whether the flag takes a value, as reported by the binary's own parser. */
export type ProbedArity = "none" | "one" | "unknown";

/** What a probe concluded about one flag on the installed binary. */
export type FlagProbeVerdict =
  /** The binary rejected the flag itself. */
  | { kind: "absent" }
  /** The flag exists and constrains its value; these are the accepted values. */
  | { kind: "present"; arity: ProbedArity; values: readonly string[] }
  /** The flag exists; no enum to enforce (or none the parser disclosed). */
  | { kind: "present"; arity: ProbedArity; values: null }
  /**
   * The probe could not tell. Under the fail-open policy this must stay
   * DISTINCT from `absent`: absent is evidence about the binary, unparsed is
   * evidence about our parser, and treating the second as the first is how a
   * discovery system starts silently removing capability.
   */
  | { kind: "unparsed"; reason: string };

/** Interpret a CLI's stderr from a deliberately-invalid probe invocation. */
export function interpretProbeOutput(stderr: string): FlagProbeVerdict {
  const text = stderr.trim();
  if (!text) return { kind: "unparsed", reason: "probe produced no diagnostic output" };

  // clap: `error: unexpected argument '--nope' found`
  if (/unexpected argument/i.test(text)) return { kind: "absent" };

  // The flag exists but takes NO value, so supplying one is "unexpected value".
  // Only the inline `=` form surfaces this; see buildProbeArgv.
  // clap: `unexpected value 'ZZZ' for '--always-approve' found; no more were expected`
  if (/unexpected value/i.test(text)) return { kind: "present", arity: "none", values: null };

  // clap: `invalid value 'ZZZ' for '--mode <MODE>'\n  [possible values: a, b]`
  const possible = /\[possible values:\s*([^\]]+)\]/i.exec(text);
  if (possible) {
    const values = possible[1]
      .split(",")
      .map(v => v.trim())
      .filter(Boolean);
    return { kind: "present", arity: "one", values };
  }
  // An invalid-value complaint with no enumerated set still proves the flag
  // exists and constrains its value; we just do not know the set.
  if (/invalid value/i.test(text)) {
    // Constrains its value, so arity is one, but the set was not disclosed.
    return { kind: "present", arity: "one", values: null };
  }

  // Anything else means the parser moved PAST our flag and failed on the
  // deliberately-missing prompt instead, so the flag was accepted.
  return { kind: "present", arity: "one", values: null };
}

/**
 * Build the argv for a safe probe of one flag.
 *
 * INLINE `=` FORM, DELIBERATELY. The space form (`--flag ZZZ --anchor`) cannot
 * distinguish a boolean flag from a value-taking one: the sentinel is consumed
 * as a positional and both produce identical stderr. The inline form makes the
 * probe a FOUR-way discriminator that also yields arity. Measured on grok 1.0.4:
 *
 *   --not-a-real-flag=ZZZ  -> "unexpected argument"                  ABSENT
 *   --always-approve=ZZZ   -> "unexpected value ... no more were
 *                             expected"                              present, arity none
 *   --permission-mode=ZZZ  -> "invalid value ... [possible values:]" present, arity one, enum
 *   --effort=ZZZ           -> falls through to the anchor error       present, arity one, no enum
 *
 * All four dialects in play accept `--flag=value` (clap, commander, argparse and
 * Go's flag), so one form covers all seven providers without a per-provider
 * branch, which the policy forbids.
 *
 * SAFETY IS STRUCTURAL. The real invariant is NOT "the anchor must take a
 * value", it is:
 *
 *     NO PROBE ARGV MAY CONTAIN A TOKEN THAT DOES NOT BEGIN WITH `-`.
 *
 * That is what the `claude completion` billing incident actually violated:
 * `completion` was a bare token, so it became a PROMPT and reached the model.
 * A bare token is the only thing that can be consumed as a positional and turn
 * a probe into a real request. The inline form has no bare token by
 * construction, and `assertProbeArgvCannotRun` enforces it.
 *
 * `anchorFlag` should require a value, so the invocation additionally fails on
 * the missing anchor value. That is defence in depth, not the primary guard.
 */
export function buildProbeArgv(
  flag: string,
  anchorFlag: string,
  sentinel = "ZZZ_GATEWAY_PROBE"
): string[] {
  const argv = [`${flag}=${sentinel}`, anchorFlag];
  assertProbeArgvCannotRun(argv);
  return argv;
}

/**
 * Throw unless every token is option-shaped.
 *
 * A probe is only safe if the CLI cannot reach dispatch, and the one thing that
 * lets it reach dispatch is a bare token being taken as a positional argument.
 * Enforced here rather than trusted to the caller, because the failure mode is
 * a billed model call and a possible side effect, not a wrong answer.
 */
export function assertProbeArgvCannotRun(argv: readonly string[]): void {
  for (const token of argv) {
    if (!token.startsWith("-")) {
      throw new Error(
        `unsafe probe argv: token ${JSON.stringify(token)} is not option-shaped and could be ` +
          `consumed as a positional, turning the probe into a real invocation`
      );
    }
  }
}
